### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by egorsmkv** [facebookresearch/dadaptation#4]
I am integrating `dadaptation` to `transformers` library (my fork - https://github.com/egorsmkv/transformers, and the commit - https://github.com/egorsmkv/transformers/commit/ec11e51c18bf0e3f120cbc09f675b42db2f1f640) 

When I start training (fine-tuning a wav2vec2 model for speech recognition), I am getting this exception:

```
Traceback (most recent call last):
  File "../../train.py", line 335, in <module>
    main()
  File "../../train.py", line 331, in main
    trainer.train(input_arg.get("resume", None))
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/transformers-4.26.0.dev0-py3.8.egg/transformers/trainer.py", line 1556, in train
    return inner_training_loop(
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/transformers-4.26.0.dev0-py3.8.egg/transformers/trainer.py", line 1866, in _inner_training_loop
    self.scaler.step(self.optimizer)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 341, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 288, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/yehor/Tools/anaconda3/envs/my/lib/python3.8/site-packages/dadaptation/dadapt_adam.py", line 160, in step
    d_hat = (sksq_weighted/(1-beta2) - gsq_weighted)/sk_l1
ZeroDivisionError: float division by zero
``` 

Params:

```
{'activation_dropout': 0.1,
 'attention_dropout': 0.0,
 'batch': 8,
 'common_voice_set': 'mozilla-foundation/common_voice_8_0',
 'custom_set': '/home/yehor/ext-disk/w2v2-train/ukr-broadcast/cleaned_train.csv',
 'custom_set_eval': '/home/yehor/ext-disk/w2v2-train/training_set.csv',
 'eval_common_voice_set': 'mozilla-foundation/common_voice_8_0',
 'eval_steps': 200,
 'feat_proj_dropout': 0.0,
 'grad_accum': 8,
 'group_by_length': True,
 'hidden_dropout': 0.0,
 'ignore_data_skip': False,
 'learning_rate': 1.0,
 'logging_steps': 20,
 'mask_feature_length': 64,
 'mask_feature_prob': 0.25,
 'mask_time_length': 10,
 'mask_time_prob': 0.75,
 'num_proc': 5,
 'num_train_epochs': 500,
 'optim': 'dadapt_adamw',
 'overwrite_output_dir': False,
 'tokenize_config': './',
 'xlsr_config': 'Yehor/wav2vec2-xls-r-300m-uk'}
```

What can it be?

**Comment by adefazio** [comment]
Is it possible that on the first step, the lr passed in is zero? That might occur if you are using a linear learning rate warmup, some codebases I've seen do a linear warmup from 0 to something, starting exactly at zero. I should add a warning for this case and handle it explicitly.

**Comment by egorsmkv** [comment]
Yes, it is possible.

All parameters during training:

```
TrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=8,
eval_delay=0,
eval_steps=200,
evaluation_strategy=steps,
fp16=True,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=8,
gradient_checkpointing=True,
greater_is_better=False,
group_by_length=True,
half_precision_backend=cuda_amp,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=1.0,
length_column_name=lengths,
load_best_model_at_end=True,
local_rank=-1,
log_level=passive,
log_level_replica=passive,
log_on_each_node=True,
logging_dir=Yehor/wav2vec2-xls-r-300m-uk-/home/yehor/ext-disk/w2v2-train/ukr-broadcast/cleaned_train.csv/runs/Jan23_20-35-18_desktop,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=20,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
no_cuda=False,
num_train_epochs=500,
optim=dadapt_adamw,
optim_args=None,
output_dir=Yehor/wav2vec2-xls-r-300m-uk-/home/yehor/ext-disk/w2v2-train/ukr-broadcast/cleaned_train.csv,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=8,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['tensorboard'],
resume_from_checkpoint=False,
run_name=Yehor/wav2vec2-xls-r-300m-uk-/home/yehor/ext-disk/w2v2-train/ukr-broadcast/cleaned_train.csv,
save_on_each_node=False,
save_steps=200,
save_strategy=steps,
save_total_limit=2,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=500,
weight_decay=0.0,
xpu_backend=None,
)
```

**Comment by adefazio** [comment]
Ok, I will add code to handle that case. Hopefully today, I'll let you know.

**Comment by adefazio** [comment]
Try the latest code in main, I've added a simple conditional to skip those lines when the LR is 0.

**Comment by egorsmkv** [comment]
It works! Thank you, @adefazio !
